### ISSUE TITLE
Change context type based on authScopes check

### ISSUE THREAD

**Issue by mmahalwy** [hayes/giraphql#101]
Not sure if this is possible to solve but I am noticing this challenge.

Give this builder:
```ts
type Context = { user?: User };

const builder = new SchemaBuilder<{
 Context: Context;
AuthScopes: {
    public: boolean;
    authenticated: boolean;
};
}>({
  plugins: [ScopeAuthPlugin, ValidationPlugin],
  authScopes: async ({ user, req }) => ({
    public: true,
    authenticated: !!user,
})
```

Then query:
```ts
builder.queryField('organizations', (t) =>
  t.field({
    type: [UserObject],

    authScopes: {
      authenticated: true,
    },
    resolve: (_root, _arg, { user }) => {
      console.log(user) // technically, because of auth scopes, the user should not be undefined 
    }
  })
);
```

Notice that we check `authenticated` authScope where we check for the presence of the user in the context. When using the context within a query, expectation (since we checked it on authScopes) is that `user` is not `undefined`.

**Comment by hayes** [comment]
Yeah, this is definitely something I would love to have a solution for.  With the plugin system I currently have, sibling fields (like auth scopes) don't have a way to affect the types of a resolver.  You basically need an additional generic slot each time you want to add a feature like that, so it's not something I have found a good way to do in a pluggable way. 

One way we could work around this would be to add a new field method (eg t.authField() that can take the additional generic, and apply it to the resolver.  Not sure how you would configure what gets changed about context though.

**Comment by hayes** [comment]
I suppose you could have a way to define per-scope context shapes in the builder setup.

**Comment by mmahalwy** [comment]
Maybe in the builder, just like we have a mapping for auth scopes
```ts
AuthScopes: {
    public: boolean;
    authenticated: boolean;
};
``` 

perhaps there could be something there where we also map the Context given the scope? So:
```
AuthScopes: {
    public: {user?: User };
    authenticated: { user: User };
};
```

**Comment by hayes** [comment]
Not sure if this actually a good idea, but I put together a prototype here: https://github.com/hayes/giraphql/pull/102 Don't have time document it, but it does work.  It doesn't really do anything other than let you specify contexts for your auth scopes (only applied when you use the `t.authField` method (let me know if you have a better name)

**Comment by mmahalwy** [comment]
sounds good. 👀
