### ISSUE TITLE
Relay mutation builder return type

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#110]
I had a situation where I wanted to share an input type between a mutation created with the relay mutation helper and one without. The relay mutation builder currently returns void and the input type string was not resolving, irrespective of load order. Would it be possible to return a structure with the generated object refs or somehow resolve the string resolution?

**Comment by hayes** [comment]
This sounds reasonable, should be pretty straight forward to implement

**Comment by hayes** [comment]
released a preview version that fixes this in #113

**Comment by jamiehodge** [comment]
Thank you!
