### ISSUE TITLE
Dataloader plugin load signature

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#111]
The dataloader plugin uses the dataloader `loadMany` function, which forces the return type of the load function to be `(T | Error)[]`. Lee Byron has written that he regretted implementing what is essentially a convenience wrapper of `Promise.all` (https://github.com/graphql/dataloader/issues/41#issuecomment-249330782). It would be very nice to be able to return `(T | null)[]` to express not found, but that is only possible if the plugin used `Promise.all` and dataloader's `load` function. I'm still not sure what I think the right pattern is, but I find the `Error` mapping/handling to be quite noisy.

**Comment by hayes** [comment]
returning nulls for load is designed to already work the way you want, but is not type-safe.  If a load for a type returns nulls, I don't have a way to force fields that return that type to be nullable (or have nullable items if its a list field).

Would you be interested in a flag you can set on a builder that adds nulls as valid items in a loads return function? 

In the mean time, you can work around this by just casting your return to be typed as an array that doesn't include nulls, and everything else should work.  If it doesn't there might be a bug I am not aware of.

**Comment by jamiehodge** [comment]
I'll give this a try and get back to you.
