### ISSUE TITLE
resolveArrayConnection type

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#119]
Given the filtering of nulls within resolveArrayConnection, wouldn't you expect the array input type to be `(T | null)[]` and the output be `T`?

**Comment by hayes** [comment]
resolve connection doesn't do any filtering, maybe misunderstood the question

**Comment by hayes** [comment]
I think I see what you mean, the edge should be nullable, but the node should not.

**Comment by hayes** [comment]
should be fixed in the latest release
