### ISSUE TITLE
mutationField

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#14]
Thank you for such a nice alternative to tools like nexus!

I might be mistaken, but it appears as though giraphql is unhappy if I build a mutationField without also building the mutationType (with empty args).

**Comment by hayes** [comment]
Yup, that is correct.  I've thought about trying to fix that, but in general, you need to define a type to be able to add fields to it.

The reason for that is that all options fields in giraphql are extensible by plugins, and plugins can add required fields.  While I could just create the mutation type the first time a mutation field is added with empty args, this would break if a plugin added a required property to the options for the mutation type.  The required empty options arguments are definitely a bit of a weird point in the API, but I think the power it gives to extensions is very powerful.  I should probably add some more docs around this.

**Comment by jamiehodge** [comment]
That makes sense.

In general, I'm still trying to grapple with how best to work with the (mutating) builder pattern. I was considering exporting `buildFoo(builder)` functions from each file and then evaluating those at the top level. 

While it's certainly convenient, it would be nice if there were alternatives to the builder.

**Comment by hayes** [comment]
Definitely something I am considering.  Early versions used a more immutable pattern where you would create types and fields and then explicitly merge them I to a schema after they were a defined.   There were a large number of pain points with this approach that I haven't figured out how to improve, but I am open to further exploration.

Can you elaborate on why you need an immutable builder pattern (testing?, multiple schemas?, reusability?).  I know there are some good reasons for it, but for a lot of use cases the mutable pattern used should work.  The order things are defined shouldn't matter, so unless you are trying to create multiple versions of the same schema, or use the same types in multiple schemas, I'm not sure what the intent of using wrapper functions would be.

**Comment by jamiehodge** [comment]
I bumped into an issue where I had to export an enum ref and then use it as a mutation arg type. That made me worry that circular dependencies would quickly crop up.

The short answer is that schemas become unwieldy if they aren't divided across separate files and that appears to mean inter-file references as it is, which sounds like a circular dependency.

I guess another point would be that because we define the source types at the top level with the builder, the grouping of concerns feels a bit unnatural.

**Comment by hayes** [comment]
Gotcha.  Giraphql has some internal logic to help resolve circular references, as long as all the files with definitions are imported before you generate the schema from the builder it should all just work.  I generally define the builder in a file on its own, then have a separate "schema" file that imports all the files that have type/field definitions.  I tried to make it very hard to run into circular dependency issues with the API design, but if you have a specific example, I can take a look and see if either I overlooked something.  I have implemented multiple schemas with hundreds of interconnected types, spread across a large number of files and haven't had any issues with circular references.

**Comment by hayes** [comment]
The one exception to the above us that you are still limited by normal JS module circular dependency rules.  This is normally not an issue because often reference to other types (like when used as args, or field types) are used inside a function that is not immediately invoked so circular references are given a chance to resolve.  That is part of why fields are always  defined with a function that returns the fields.

```ts
builder.queryFields(t  => ({
  // Evaluated when needed, so circular references used here won't cause issues 
}))
```

**Comment by jamiehodge** [comment]
I appreciate you being so responsive. I guess the only followup to this would be that it appears as though enums can't be referenced as type strings in mutation arguments at the moment. I also found that I needed to be explicit about the generics when using enumType, i.e. `builder.enumType<string, Record<string, { value: Foo }>>` to avoid the value being inferred as string.

**Comment by hayes** [comment]
You are correct about not being able to reference enum types via a string.  There are actually several different ways to define an enum described here https://giraphql.com/guide/enums

When using a typescript enum to define your giraphql enum, you have 2 options in mutation args, you can either use the reference returned from the builder, or you can use the ts enum.  I could support using a string as a reference, but it would require passing a mapping into the generic params when creating the builder, which gets unwieldy very quickly, and adds a lot of overhead.  Importing the ts or giraphql enum and using that as a reference in my experience tends to be simpler, and with automatic imports in most editors should just as easy. 

Regarding the need for explicitly passing in the generic types when creating an enum, that should not happen when using a TS enum, of you are defining the enum using an object or array with strings, you can use `as const` either on the while array/object, or on the individual strings, which should make all the inference work correctly.

**Comment by jamiehodge** [comment]
The issue is that we generally use unions, not enums in our models.

**Comment by hayes** [comment]
Not sure I understand the issue, can you share a slightly more complete example of your model and how you are defining the graphql type?

**Comment by hayes** [comment]
If you are using ts unions:

```ts
type YourUnion = 'foo' | 'bar'

builder.enumType('TypeName', { values: ['foo', 'bar'] as YourUnion [] })
// Or
builder.enumType('TypeName', { values: ['foo', 'bar'] as const })

**Comment by jamiehodge** [comment]
Impressive phone coding skills. I'm going to close this issue. Thank you.
