### ISSUE TITLE
[Dataloader] `args` and `info` are not passed to the load method

### ISSUE THREAD

**Issue by dekimasoon** [hayes/giraphql#154]
First of all, thanks for the great library!

I've made an issue that I would like the load method of the Dataloader plugin to pass info(GraphQLResolveInfo) and args.

I am trying to convert GraphQLResolveInfo into a Prisma select clause so that I can optimize the get column and get the related tables automatically.

I want to do the same thing for fields that require a Dataloader, and that is why we want GraphQLResolveInfo to be passed to the load method.

I don't have a specific use for args yet, but I don't think there is any harm in passing it, so I would like it to be passed along.

**Comment by dekimasoon** [comment]
@Jomik @hayes Thank you. I'm going to try out some of the features you've implemented!

> It looks like what you are trying do gas a lot of overlap with the Prisma plugin (except it does not integrate with dataloader)

That's right. We are considering this way because it can be achieved in a framework-independent way, but Prisma Plugin is so great, so I may switch to that. Thank you for all your support!

**Comment by boenni23** [comment]
@hayes, this is an old issue, but don't you think having args in the load function would be nice?
Having something like this:
```
builder.objectType(User, {
  name: 'User',
  fields: (t) => ({
    id: t.exposeID('id'),
    posts: t.field({
      type: [Post],
      nullable: false,
      args: {
        filter: PostWhereInput,
        orderBy: PostOrderByInput,
      },
      resolve: (parent, args, ctx) => {
        return ctx.db.post.findMany({
          where: {
            ...args.filter,
            authorId: parent.id,
          },
          orderBy: args.orderBy,
        })
      }
    })
  })
})
```


For the data loader you would also need the args for an optimized version
```

builder.objectType(User, {
  name: 'User',
  fields: (t) => ({
    id: t.exposeID('id'),
    posts: t.field({
      type: [Post],
      nullable: false,
      args: {
        filter: PostWhereInput,
        orderBy: PostOrderByInput,
      },
      load: (ids: string[], args, ctx) => {
        return ctx.loadFilteredPosts(ids, args)
      },
      resolve: ({id}) =>id
    })
  })
})
```

Going to the Database in the resolve function in order to get the ids in the first place would make this request slower in most cases.
