### ISSUE TITLE
[ESM] Plugin Prisma errors on graphql/execution/values import

### ISSUE THREAD

**Issue by pixelmund** [hayes/giraphql#158]
Hey, i migrated to the new prisma plugin version and it stopped working. 
I see that you changed the way you bundle the esm versions, so this is the only failing case:

https://github.com/hayes/giraphql/blob/d4d4fad976b392399257b7e2cf2478fb6c4f4fb8/packages/plugin-prisma/src/util/map-includes.ts#L14

The import from `graphql/execution/values` is missing a `.js` extension or maybe there is another way to import `getArgumentValues`.

**Comment by hayes** [comment]
should be fixed now
