### ISSUE TITLE
Manual dataloader usage results in incorrect items

### ISSUE THREAD

**Issue by timcole** [hayes/giraphql#169]
Hello! My team @spaceflight-live is trying to switch to giraphql from type-graphql but we've noticed an issue with dataloaders.
We have a series of loadableObjects and one object can load another.

For example, we have a LaunchObject which is a loadableObject that has a vehicle has a field, vehicle is a field with a type of VehicleObject, VehicleObject is also a loadableObject.

```ts
    vehicle: t.field({
      type: VehicleObject,
      resolve: async ({ vehicle_id }, _, context) => {
        const l = await context.load(VehicleObject, vehicle_id);
        console.log(`asked for`, vehicle_id, `-- got`, l.id, l.name);
        return l;
      },
    }),
```

Here is the field (note this issue isn't limited to just this it's all loadableObjects in a loadableObject).

When querying for launches (unless there's only one results) everything is not where it's supposed to be. The print out from the console.log above results in

```
asked for cUZLoRuasxn -- got bK0_dE3mw-1 Falcon 9
asked for 5Bpbheyvohg -- got 5Bpbheyvohg Long March 2C/YZ-1S
asked for bK0_dE3mw-1 -- got zDxPyMmY70m Epsilon
asked for q2IC7e_eR-u -- got wl2VOAWRorB H-IIA 202
asked for 890YR2IolqE -- got cUZLoRuasxn Hapith I
asked for zDxPyMmY70m -- got stz_wajqstB Ariane 5 ECA
asked for I4I2UEeVRta -- got qVz3EdJfzjO Atlas V 541
asked for wl2VOAWRorB -- got q2IC7e_eR-u Soyuz 2.1b/Fregat-M
asked for stz_wajqstB -- got 890YR2IolqE Atlas V 401
asked for qVz3EdJfzjO -- got I4I2UEeVRta Soyuz 2.1b
asked for bK0_dE3mw-1 -- got zDxPyMmY70m Epsilon
asked for 890YR2IolqE -- got cUZLoRuasxn Hapith I
asked for bK0_dE3mw-1 -- got zDxPyMmY70m Epsilon
asked for q2IC7e_eR-u -- got wl2VOAWRorB H-IIA 202
```

cacheResolved's are set, initContextCache is also in the context factory function

**Comment by hayes** [comment]
Hey, this looks like it would be a pretty serious bug.  I have a theory that might be an easy fix IF it's the issue.  If. You are using loadMany in your object can you confirm you are retuning tye array of loaded items in the same order as they are being requested?  This is a requirement of dataloader, since it does not know how to map objects to their IDs, it uses the index in the returned array to identify them.

**Comment by hayes** [comment]
If that is not the issue, an example of how the loadable object is implemented would be helpful

**Comment by hayes** [comment]
Dataloader docs were written with too many assumptions about the user being familiar with the dataloader library.  This section describes the requirements of the load function in more detail https://github.com/graphql/dataloader#batch-function

**Comment by timcole** [comment]
Absolute rockstar, good thinking!

It looks like when I sort the results from our output everything appears to be correct.

Test loader from vehicles with resorting the results to match the order of input ids
```
  load: async (ids: string[]) => {
    const test = await prisma.vehicle.findMany({ where: { id: { in: ids } } });
    test.sort((a, b) => ids.indexOf(a.id) - ids.indexOf(b.id));
    return test;
  }
```
```
asked for cUZLoRuasxn -- got cUZLoRuasxn Hapith I
asked for 5Bpbheyvohg -- got 5Bpbheyvohg Long March 2C/YZ-1S
asked for bK0_dE3mw-1 -- got bK0_dE3mw-1 Falcon 9
asked for q2IC7e_eR-u -- got q2IC7e_eR-u Soyuz 2.1b/Fregat-M
asked for 890YR2IolqE -- got 890YR2IolqE Atlas V 401
asked for zDxPyMmY70m -- got zDxPyMmY70m Epsilon
asked for I4I2UEeVRta -- got I4I2UEeVRta Soyuz 2.1b
asked for wl2VOAWRorB -- got wl2VOAWRorB H-IIA 202
asked for stz_wajqstB -- got stz_wajqstB Ariane 5 ECA
asked for qVz3EdJfzjO -- got qVz3EdJfzjO Atlas V 541
asked for bK0_dE3mw-1 -- got bK0_dE3mw-1 Falcon 9
asked for 890YR2IolqE -- got 890YR2IolqE Atlas V 401
asked for bK0_dE3mw-1 -- got bK0_dE3mw-1 Falcon 9
asked for q2IC7e_eR-u -- got q2IC7e_eR-u Soyuz 2.1b/Fregat-M
```

**Comment by hayes** [comment]
I might add an option to handle the sorting automatically.  The approach above is a little brittle, and will fail of any of the IDs are not found.  I would probably do something like `ids.map(id => list.find(vehicle => vehicle.id === I'd))`

**Comment by timcole** [comment]
Either an automatic option or at least a note in the docs would be awesome!
Thanks for that suggestion. Though all our data is to be assumed valid, will definitely switch to that for those oh crap moments hah.

**Comment by hayes** [comment]
Adding the sort option in https://github.com/hayes/giraphql/pull/170, but it may be a bit before I get around to a release because I am in the middle of a road trip with very spotting internet.
