### ISSUE TITLE
enumType not using assigned value on enum

### ISSUE THREAD

**Issue by theogravity** [hayes/giraphql#173]
If I have a situation where I am aliasing a value out in an enum, it doesn't get picked up by the enumType definition.

For example:

```ts
enum LogLevels {
  Info = 'info',
  Warn = 'warn',
  Error = 'error
}

gqlBuilder.enumType(LogLevels, {
  name: 'LogLevels',
});
```

The output for the schema will look like this:

```ts
enum LogLevels {
  Info
  Warn
  Error
}
```

When it should be:

```ts
enum LogLevels {
  info
  warn
  error
}
```

**Comment by hayes** [comment]
This is the expected behavior.  The enum names are what shows up in the graphql schema, and the values (lower case version) is what you will see at run time in your code.

**Comment by theogravity** [comment]
Is there a way to manually assign them like how we map resolvers to the base model?

**Comment by hayes** [comment]
There isn't a built in way currently to re-map values as names.  You can do something like this:

```ts
enum LogLevels {
  Info = 'info',
  Warn = 'warn',
  Error = 'error',
}

builder.enumType('LogLevels', {
  values: {
    info: {
      value: 'info',
    },
  } as const,
});

builder.configStore.associateRefWithName(LogLevels, 'LogLevels');

builder.queryField('logLevel', (t) =>
  t.field({
    type: LogLevels,
    args: { level: t.arg({ type: LogLevels, required: true }) },
    resolve: (root, args) => {
      console.log(args.level);

      return args.level;
    },
  }),
);
```

This will let you use the LogLevels enum, to reference a manually defined graphql enum type.
If this is something you need to do frequently, it would be easy to write a plugin that adds a method like `enumFromValues` to the builder or something.  This method would basically just do the above

**Comment by theogravity** [comment]
Thanks! That should help!

**Comment by IslamWahid** [comment]
@theogravity any updates regarding that? did you manage to create that plugin?

**Comment by neongreen** [comment]
> The enum names are what shows up in the graphql schema, and the values (lower case version) is what you will see at run time in your code.

Hitting this as well, but for me the lowercase values are _not_ what shows up at runtime in my code. Or I might be misinterpreting this. But I'm getting upper-case responses from the backend and from Apollo Client.

**Comment by neongreen** [comment]
Maybe what was meant is that I'll see lowercase values in the Pothos part of the code, but definitely not in the frontend side of the code.

**Comment by hayes** [comment]
Again, this sounds like the expected behavior.  If you are looking for something else, you may need to define the enum manually.


The way it works is that the enum names (upper case) are what end up in the schema, and this is what will be returned in responses and what you will see on the client side.  The ts enum values (lower case version, right hand side) is the internal version, this is what you will see in your resolvers on the server.

**Comment by theogravity** [comment]
I never wrote a plugin for this. I just used the custom definition route as mentioned above. If you're trying to reconcile with type generation, we use `graphql-codegen` and manually mapped the definitions so the generated types were consistent:

```
  generated/graphql-types.ts:
    schema: 'generated/schema.graphql'
    plugins:
      - typescript
      - typescript-resolvers
    config:
      enumValues:
        CustomMappedEnum: '../src/enums#CustomMappedEnum'
```

See this post for more info

https://stackoverflow.com/questions/65519093/graphql-codegen-enum-with-custom-key-value
