### ISSUE TITLE
Depth limit support

### ISSUE THREAD

**Issue by bigint** [hayes/giraphql#180]
It would be great if we have depth limit support and also other security measures mentioned in https://www.apollographql.com/blog/graphql/security/securing-your-graphql-api-from-malicious-queries

**Comment by hayes** [comment]
Having a query complexity plugin is on my to-do list.  GiraphQL does not actually handle executing queries, so the best it can do is wrap resolvers for query fields and do checks when those top level resolvers are executed.  This is probably one of the next plugins I'll work on.

In the mean time, there are lots of ways to do this outside of GiraphQL.  The easiest would probably be with something like graphql envelope which has a depth limit plugin. The package in the post above can also be used with GiraphQL.

**Comment by bigint** [comment]
Thanks a lot, I just tried this plugin `graphql-depth-limit` and it works with graphql-helix

![image](https://user-images.githubusercontent.com/69431456/134292683-05e960fe-0f09-42ea-a46b-154023bd4c32.png)

**Comment by hayes** [comment]
Complexity plugin is now available: https://giraphql.com/plugins/complexity
