### ISSUE TITLE
schemaDirectives is not working in SchemaBuilder

### ISSUE THREAD

**Issue by bigint** [hayes/giraphql#181]
![image](https://user-images.githubusercontent.com/69431456/134293953-3df6543d-26dc-407e-b796-d31c3f04c272.png)

![image](https://user-images.githubusercontent.com/69431456/134294013-c40db417-4e30-4ce2-9813-37495257c203.png)

```ts

export const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes
  Directives: DirectiveTypes
  DefaultInputFieldRequiredness: true
  Context: Context
  Scalars: {
    ID: { Input: string; Output: string | number }
    DateTime: { Input: Date; Output: Date }
    Attachments: { Input: String; Output: Prisma.JsonValue }
  }
  AuthScopes: {
    public: boolean
    user: boolean
    unauthenticated: boolean
    isStaff: boolean
  }
}>({
  defaultInputFieldRequiredness: true,
  plugins: [
    SimpleObjectsPlugin,
    ScopeAuthPlugin,
    ValidationPlugin,
    PrismaPlugin,
    RelayPlugin,
    DirectivePlugin
  ],
  prisma: { client: db },
  authScopes: async ({ session }) => ({
    public: true,
    user: !!session,
    unauthenticated: !session,
    isStaff: !!session?.isStaff
  }),
  relayOptions: {
    clientMutationId: 'omit',
    cursorType: 'String'
  },
  schemaDirectives: {
    rateLimit: createRateLimitDirective()
  }
})
```

/cc @hayes

**Comment by bigint** [comment]
I just inferred this idea from https://github.com/hayes/giraphql/issues/27#issuecomment-770941036

**Comment by hayes** [comment]
Have you looked at https://giraphql.com/plugins/directives

**Comment by bigint** [comment]
@hayes Yup but didn't work, I tried to get directives but still, it returns only four not the ratelimit one

![image](https://user-images.githubusercontent.com/69431456/134294923-36e4baa8-531f-4934-82df-be9d9c9b2c7c.png)

![image](https://user-images.githubusercontent.com/69431456/134294899-c0b8865c-9af9-49ad-bf29-40a77c07f388.png)

```ts
import './resolvers'

import fs from 'fs'
import { GraphQLSchema, lexicographicSortSchema, printSchema } from 'graphql'
import { createRateLimitDirective } from 'graphql-rate-limit-directive'
import path from 'path'

import { builder } from './builder'

export const schema = builder.toSchema({})

createRateLimitDirective().visitSchemaDirectives(schema, {})

console.log(schema.getDirectives())

export default schema

function writeSchema(schema: GraphQLSchema) {
  const schemaAsString = printSchema(lexicographicSortSchema(schema))
  const schemaPath = path.join(process.cwd(), 'src/graphql/schema.graphql')

  const existingSchema =
    fs.existsSync(schemaPath) && fs.readFileSync(schemaPath, 'utf-8')

  if (existingSchema !== schemaAsString) {
    fs.writeFileSync(schemaPath, schemaAsString)
  }
}

if (process.env.NODE_ENV !== 'production') {
  writeSchema(schema)
}
```

**Comment by hayes** [comment]
You shouldn't pass the directives the builder, you'll need to apply them after the schema is generated with something like graphql-tools.  Directives are not a standardized part of GraphQL

**Comment by hayes** [comment]
I think that is expected.  The rate-limiting should still work

**Comment by bigint** [comment]
> I think that is expected. The rate-limiting should still work

You mean the code above? But the `@ratelimit` is not added to schema.graphql file 🤔

**Comment by hayes** [comment]
Correct, as mentioned in the docs, the directives are not visible in the printed schema

**Comment by bigint** [comment]
> Correct, as mentioned in the docs, the directives are not visible in the printed schema

But still, rate-limiting didn't work :(

![image](https://user-images.githubusercontent.com/69431456/134295685-2b3658a2-2bd4-447c-8845-6c0c1f89d28d.png)

**Comment by hayes** [comment]
Actually, it looks like that is missing from the docs... I'll have to look into that

**Comment by bigint** [comment]
BTW here is the PR I'm working on for rate limit integration https://gitlab.com/yo/devparty/-/merge_requests/238

**Comment by hayes** [comment]
Heading to sleep, so I don't have time to look at this right now.  One thing to try, you may need to set useGraphQLToolsUnorderedDirectives I think graphql tools may have been updated to not need that

**Comment by bigint** [comment]
Take care, see ya tomorrow 🤗

**Comment by hayes** [comment]
Looks like the way the rate limit visitor has changed slightly.  I've updated the docs and added a test to confirm.  See #184 (mostly unrelated, but I am updating the docs in the PR as well).
