### ISSUE TITLE
Validation plugin: Error "Intersection results could not be merged" on array fields

### ISSUE THREAD

**Issue by mmahalwy** [hayes/giraphql#186]
Could be related to this: https://github.com/colinhacks/zod/issues/636

When having validation on the input level and having an object with array of objects, get error `Intersection results could not be merged`. See:

```ts
builder.mutationField('testMutation', (t) =>
  t.field({
    type: 'Boolean',
    nullable: true,
    errors: {
      types: [ZodError],
    },
    args: {
      input: t.arg({
        type: SomeInput,
        required: true,
        validate: {
          schema: z.object({
            anArray: zod.array(zod.object({}))
          }),
        },
      }),
    },
    resolve: async () => {
      return true;
    },
  })
);
```

BUT this does work:

```ts
const inputSchema = z.object({
  anArray: zod.array(zod.object({}))
});

builder.mutationField('testMutation', (t) =>
  t.field({
    type: 'Boolean',
    nullable: true,
    errors: {
      types: [ZodError],
    },
    args: {
      input: t.arg({
        type: SomeInput,
        required: true,
      }),
    },
    resolve: async (_r, {input }) => {
      inputSchema.parse(input)
      return true;
    },
  })
);

```

**Comment by hayes** [comment]
I think there are a few different issues with array validation.  Something I obviously did not test thoroughly enough.  I think I am going to have to look into the intersection stuff, because it seems to pop up in a few different ways (mostly around validating arrays)

**Comment by mmahalwy** [comment]
Sounds good. I will keep testing things out @hayes :)

**Comment by hayes** [comment]
Fixed the other issue, but this one is a little trickier

**Comment by hayes** [comment]
pushed up a temporary workaround. It's not perfect, because the path in errors will now just be the path in the validation validation schema, not the full path if its in a nested object, but its better than nothing.

**Comment by hayes** [comment]
If you get a change, and could test if `@giraphql/plugin-validation@2.11.0` fixes this issue that would be cool (core needs to be updated too to fix the other issue)

**Comment by hayes** [comment]
fix: https://github.com/hayes/giraphql/blob/main/packages/plugin-validation/src/createZodSchema.ts#L90-L96

**Comment by mmahalwy** [comment]
Will do first thing tomorrow
