### ISSUE TITLE
[Prisma] Relation query function does not get context passed to it

### ISSUE THREAD

**Issue by Brendonovich** [hayes/giraphql#200]
According to [the docs](https://giraphql.com/plugins/prisma#filters-sorting-and-arguments), if a function is provided to the `query` option of a relation it should receive both the field's arguments and the request context. As of `@giraphql/plugin-prisma` 0.1.10, this is not the case, as the arguments are passed correctly but request context is undefined (presumably as it is not passed in).

The following relation does not execute as `ctx` is undefined:
```ts
t.relation("classes", {
  query: (_args, ctx) => ({
    where: {
      teachers: {
        some: {
          id: ctx.user.id,
        },
      },
    },
  }),
})
```

**Comment by Brendonovich** [comment]
@hayes Works in my application now, thanks for the fix

**Comment by hayes** [comment]
fixed should be released now
