### ISSUE TITLE
Getting `Cannot read properties of undefined (reading 'Symbol(GiraphQL.contextCache)')` after upgrading to GraphQL 16 and Helix 1.9.0

### ISSUE THREAD

**Issue by bigint** [hayes/giraphql#210]
Getting `Cannot read properties of undefined (reading 'Symbol(GiraphQL.contextCache)')` after upgrading to GraphQL 16 and Helix 1.9.0

/cc @hayes

**Comment by bigint** [comment]
Is this because of https://github.com/contrawork/graphql-helix/issues/90 ?

**Comment by hayes** [comment]
Yes, this is a bug in the latest version of graphql-helix
