### ISSUE TITLE
GraphQLUpload scalar implementation

### ISSUE THREAD

**Issue by vekonylaszlo** [hayes/giraphql#213]
Hey👋

I'm trying to create a file upload mutation based on the [ApolloGraphQL](https://www.apollographql.com/docs/apollo-server/data/file-uploads/) documentation.
I can't figure out, how should I map the `GraphQLUpload` to the `Upload` scalar. 

In the `builder` file, I added a new scalar like this:
```
Scalars: {
    ...
    Upload: { Input: Upload; Output: Upload; }
  };
```

And then i tried to add the `GraphQLUpload` like this:
```
builder.addScalarType("Upload", GraphQLUpload, {});
```
But I get an error message:
`Argument of type 'GraphQLScalarType' is not assignable to parameter of type 'GraphQLScalarType<unknown, unknown>'.
  Type 'GraphQLScalarType' is missing the following properties from type 'GraphQLScalarType<unknown, unknown>': specifiedByURL, [Symbol.toStringTag]`

Can you give me a hint on how should I solve this?
Thank you very much!

**Comment by hayes** [comment]
My guess is you have to copies of graphql in your dependency graph.

This issue is probably related: https://github.com/graphql/graphql-js/issues/3156

I would highly recommend using resolutions (if you are using yarn or pnpm) to ensure you only have 1 version of graphql

**Comment by vekonylaszlo** [comment]
You were right! Thank you for helping out!
