### ISSUE TITLE
Support importing from Skypack

### ISSUE THREAD

**Issue by deckchairlabs** [hayes/giraphql#217]
I would love to be able to `import SchemaBuilder from "https://cdn.skypack.dev/@giraphql/core?dts"` into my Deno environment.

Although looks as though there are issues with Typescript types not loading correctly, I think this is due to the package.json not referencing any type definitions https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by hayes** [comment]
I would recommend not using skypack version of giraphql there are a number of other issues that will cause it not to work. GiraphQLs plugin system is not well suited to that specific style of import.

Instead use the deno.land version: https://deno.land/x/giraphql@%40giraphql%2Fplugin-prisma%400.11.1 The tagging is kinda weird and I haven't found a good way to set what tags show up as versions.

The deno version is generated from the same source through a custom script that solves some of the deno specific issues I ran into.

**Comment by deckchairlabs** [comment]
Ah right, I've been able to use core package with no problems beside the type issues, probably because I'm not using any GiraphQLs plugins currently.

Yeah I noticed the tag issue, I'll see if I can switch over to the deno.land version

**Comment by hayes** [comment]
@deckchairlabs you can probably import from https://www.skypack.dev/view/@giraphql/deno as well

**Comment by deckchairlabs** [comment]
> @deckchairlabs you can probably import from https://www.skypack.dev/view/@giraphql/deno as well

Ah yes! That works perfectly.

For reference

```ts
import SchemaBuilder from "https://cdn.skypack.dev/@giraphql/deno/packages/core/mod.ts";
```
