### ISSUE TITLE
Prisma plugin generation issue

### ISSUE THREAD

**Issue by RicardoValero95** [hayes/giraphql#222]
I recently updated `prisma` and `@prisma/client`  from `3.4.1` to `3.5.0`

I tried it with `@giraphql/plugin-prisma` both `0.10.0` and `0.12.1`

`schema.prisma`
```prisma
generator giraphql {
  provider     = "prisma-giraphql-types"
  clientOutput = "@prisma/client"
  output       = "./giraphql-types.ts"
}
```

My generated types look like this 

`giraphql-types.ts`
```ts
import type { Prisma as , Test as , User as , Profile as , Token as , Session as , Role as , Email as , Chat as , Message as , Location as , Lot as , LotResult as , Box as , Product as , ProductBoxConfig as , ProductBoxResult as , Protocol as , DeviceType as , Device as , LabelTemplate as  } from "@prisma/client";
```
I simply removed the `as` and it worked. 

```ts
import type { Prisma, Test, User, Profile, Token, Session, Role, Email, Chat, Message, Location, Lot, LotResult, Box, Product, ProductBoxConfig, ProductBoxResult, Protocol, DeviceType, Device, LabelTemplate } from "@prisma/client";
```

**Comment by hayes** [comment]
Looks like this is actually not related to the prisma upgrade.  I am guessing you upgraded ts to 4.5 as well?  Looks like there are some breaking changes in the typescript API I am using to generate code.

**Comment by hayes** [comment]
@RicardoValero95 if you upgrade now it should be fixed if that was actually what was causing your issue.  Either way, new version will require `typescript@>`4.5.2`

**Comment by hayes** [comment]
Going to close this since I believe it is now fixed. Let me know if you are still having issues

**Comment by RicardoValero95** [comment]
Yes it is fixed, sorry for not responding! Thanks, great work!
