### ISSUE TITLE
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by bigint** [hayes/giraphql#227]
Getting this while using https://giraphql.com/plugins/complexity

Happening while getting introspection query

![image](https://user-images.githubusercontent.com/69431456/142761302-7b35bdf9-4211-42f4-ad31-d99fbc3b338d.png)

/cc @hayes

**Comment by bigint** [comment]
https://gitlab.com/yo/devparty/-/merge_requests/862/diffs

**Comment by hayes** [comment]
this should be fixed now
