### ISSUE TITLE
[Docs] Missing Guide topics

### ISSUE THREAD

**Issue by smolattack** [hayes/giraphql#231]
Certain topics under the Guide section on the docs site are missing. I'm almost certain that you could navigate to the App Layout and Patterns guides from the main site a few days ago.
If I understand how this should work, the following are also missing:

Generating Client Types
Deno
Troubleshooting
Using Plugins
Writing Plugins

![image](https://user-images.githubusercontent.com/74571687/143032112-a15d2277-a332-4ce4-a214-316e7a00e0dc.png)

**Comment by hayes** [comment]
My bad! Looks like something broke when I upgraded gitbook yesterday, and only an old version of the docs was available (for version 1.5).
