### ISSUE TITLE
Unions when using inputRef cause errors

### ISSUE THREAD

**Issue by mmahalwy** [hayes/giraphql#240]
We have a union that we are using `inputRef` with which causes a typing error:

![image](https://user-images.githubusercontent.com/3749095/145643104-981f8f36-e62d-4474-ab10-d6b5636e2678.png)

Problem is stemming out of having some fields required in one option in the union, and not required (optional) in another. Setting `required: false` with Giraphql creates this error. 

Probably no easy work around here other than using `inputType` in exchange with `inputRef`.

**Comment by hayes** [comment]
Can you provide more context? Some code and a more complete error message would help me understand what the issue is

**Comment by mmahalwy** [comment]
@hayes apologies, my issues suck 😓 .

Here's two examples:
```ts
type SomeType = ({ a: number; b: number } | { a: null; b: null }) & { c: number };
const SomeInput = builder.inputRef<SomeType>('SomeInput').implement({
  fields: (t) => ({
    a: t.int({ required: false }),
    b: t.int({ required: false }),
    c: t.int({ required: true }),
  }),
});
```
Errors with:
```
Type '{ a: InputFieldRef<number | null | undefined, "InputObject">; b: InputFieldRef<number | null | undefined, "InputObject">; c: InputFieldRef<number, "InputObject">; }' is not assignable to type 'InputFieldsFromShape<{ a: number; b: number; c: number; } | { c: number; a?: null | undefined; b?: null | undefined; }>'.
  Type '{ a: InputFieldRef<number | null | undefined, "InputObject">; b: InputFieldRef<number | null | undefined, "InputObject">; c: InputFieldRef<number, "InputObject">; }' is not assignable to type 'InputFieldsFromShape<{ c: number; a?: null | undefined; b?: null | undefined; }>'.
    Types of property 'a' are incompatible.
      Type 'InputFieldRef<number | null | undefined, "InputObject">' is not assignable to type 'InputFieldRef<null | undefined, "InputObject">'.
        Type 'number | null | undefined' is not assignable to type 'null | undefined'.
          Type 'number' is not assignable to type 'null | undefined'.ts(2322)
```

```ts
const EnumA1 = ['A1', 'A11'] as const;
const EnumA2 = ['A2', 'A22'] as const;

const EnumA = builder.enumType('EnumA1', {
  values: [...EnumA1, ...EnumA2] as const,
});


type SomeWithEnumType = ({ a: typeof EnumA1[number] } | { a: typeof EnumA2[number] }) & {
  c: number;
};
const SomeInput = builder.inputRef<SomeWithEnumType>('SomeInput').implement({
  fields: (t) => ({
    a: t.field({ type: EnumA, required: true }),
    c: t.int({ required: true }),
  }),
});
```

errors with
```
Type '{ a: InputFieldRef<"A1" | "A11" | "A2" | "A22", "InputObject">; c: InputFieldRef<number, "InputObject">; }' is not assignable to type 'InputFieldsFromShape<{ a: "A1" | "A11"; c: number; } | { a: "A2" | "A22"; c: number; }>'.
  Type '{ a: InputFieldRef<"A1" | "A11" | "A2" | "A22", "InputObject">; c: InputFieldRef<number, "InputObject">; }' is not assignable to type 'InputFieldsFromShape<{ a: "A2" | "A22"; c: number; }>'.
    Types of property 'a' are incompatible.
      Type 'InputFieldRef<"A1" | "A11" | "A2" | "A22", "InputObject">' is not assignable to type 'InputFieldRef<"A2" | "A22", "InputObject">'.
        Type '"A1" | "A11" | "A2" | "A22"' is not assignable to type '"A2" | "A22"'.
          Type '"A1"' is not assignable to type '"A2" | "A22"'.ts(2322)
```

**Comment by hayes** [comment]
What you are trying to do is not technically valid.  It's not intentional that type-checking fails, but the types you are using to describe your inputs don't actually map correctly to how the would be described in your schema.

Given the type:
`type SomeType = ({ a: number; b: number } | { a: null; b: null }) & { c: number };`

The closest way this could be represented in graphql would be `{ a: number | null, b: number | null, c: number }`.  I'll update GiraphQL to interpret unions like this when creating an inputRef from a union type.

**Comment by hayes** [comment]
I created a [PR](https://github.com/hayes/giraphql/pull/241) with a fix/workaround.

Some tests are failing, and I think this may add more complexity to the `inputRef` logic than makes sense.

A workaround on your end is to just merge the unions yourself before passing them to the inputRef:

`export type MergeUnion<T> = keyof T extends infer U ? { [K in U & keyof T]: T[K] } : never;`

**Comment by hayes** [comment]
Latest version of GiraphQL should work as described above

**Comment by mmahalwy** [comment]
Awesome! thank you for the quick turnaround on this. Going to update on my end and test

**Comment by mmahalwy** [comment]
Hmm, I think this may have caused a regression @hayes. See:
![image](https://user-images.githubusercontent.com/3749095/145772909-c2960ac4-4d71-4200-b581-5ff9745239a5.png)

Given: 
```ts
const UpdatePolicyInput = builder
  .inputRef<Prisma.PolicyUncheckedUpdateInput & { id: string }>('UpdatePolicyInput')
  .implement({
    fields: (t) => ({
      id: t.id({ required: true }),
      name: t.string({ required: true }),
    }),
  });

builder.mutationField('updatePolicy', (t) =>
  t.field({
    type: PolicyObject,
    authScopes: { admin: true },
    args: {
      input: t.arg({ type: UpdatePolicyInput, required: true }),
    },
    resolve: async (_, { input: { id, name } }, { prisma }) => {
      // TODO: add prisma transaction and validation
      const policy = await prisma.policy.update({
        where: { id },
        data: {
          name,
        },
      });

      return policy;
    },
  })
);
```

it shows `id` as `string | {}`

**Comment by mmahalwy** [comment]
@hayes I think this caused a regression with `Date` types.

In my builder I have:
```ts
Date: {
      Input: Date;
      Output: Date;
    };
```

And whenever used in an input:
```ts
const UpdateInput = builder.inputRef<{ id: string; date: Date }>('UpdateInput').implement({
  fields: (t) => ({
    id: t.id({ required: true }),
    date: t.field({ type: 'Date', required: true }),
  }),
});

builder.mutationField('updateMutation', (t) =>
  t.field({
    type: 'Boolean',
    authScopes: { admin: true },
    args: {
      input: t.arg({ type: UpdateInput, required: true }),
    },
    resolve: async (_, { input: { id, date } }) => {
      console.log(id, date);
      return true;
    },
  })
);
```

The date object comes back as:
![image](https://user-images.githubusercontent.com/3749095/145773872-e4a686f3-7810-4f0a-8dfb-1613e00c0a83.png)

**Comment by hayes** [comment]
That's not good.  Reverting now and will release a reverted version in a minute.

**Comment by hayes** [comment]
@mmahalwy After thinking about this some more, I am not sure it's reasonable to try to support this directly.

I think using a utility like `MergeUnion` before passing the union type to inputRef is the correct solution here.  Adding union merging into `inputRef` would add some hard to document behavior that probably isn't very intuitive.  If you are using types that do not map directly to the graphql input shape, then merging/converting is something that should be left up to the application. 

Unions generally include behavior that can't be represent in graphql input types (like your example above).  I am guessing the actual type comes from a validation schema or something like that.

A possible solution for that use case would be to create a method that (for example) takes a zod schema, infers its shape, and then creates an implementable input ref from the that schema.  That method could include the logic for merging any potential schemas, allowing you to implement fields of looser (merged) type, while still typing the ref (and args/fields that use the ref) with the more accurate types that describe the parsed result.

**Comment by mmahalwy** [comment]
@hayes that makes sense. And appreciate the quick follow up on this. I agree, we can convert the unions on our end. I found this to help too: https://github.com/sindresorhus/type-fest/blob/main/source/union-to-intersection.d.ts
