### ISSUE TITLE
Complexity Plugin fails on __typename

### ISSUE THREAD

**Issue by 100BC** [hayes/giraphql#248]
Hi there, I've implemented the complexity plugin in my schema. However, I noticed a bug where the query will throw an exception if the query has a `__typename` in it.

The complexity plugin functions correctly when the query is sent from a graphql ide (Altair in my case). However, when my frontend sent the same query it failed because the frontend gql client (urql) attached `__typename` to the query. I managed to debug it to find where the code is throwing error.

In `calculate-complexity.js` on line 23:

![image](https://user-images.githubusercontent.com/73491141/146662339-44eb881a-9fd2-4fa9-a6b0-56e1a1185496.png)

eventually it selects a field that has a name.value of  `__typename` which will will throw error since the field isn't defined.

![image](https://user-images.githubusercontent.com/73491141/146662398-b5a8aed7-5806-4041-8561-d5de258478c2.png)

Manually adding `__typename` to the query will also cause the the query to fail in the graphql ide

I am unable to disable typenames from being sent from the frontend, according to [this issue](https://github.com/FormidableLabs/urql/issues/90).

Let me know if you'd like more information, and if it is a possible to fix. Thanks!

**Comment by hayes** [comment]
Thanks for reporting this! Should be fixed in the latest version.  Let me know if you run into any more issues

**Comment by 100BC** [comment]
Just upgrade and tested it. Looks like everything is working. Thanks for the quick response
