### ISSUE TITLE
[Prisma-Plugin] Type generations imports not working

### ISSUE THREAD

**Issue by baristikir** [hayes/giraphql#252]
I have recently upgraded the `@giraphql/pisma-plugin` package to the latest version from `"@giraphql/plugin-prisma": "^0.9.2"` and am facing an issue with the giraphql type generation.

My `schema.prisma` looks like this:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "darwin", "linux-musl", "linux-arm64-openssl-1.1.x"]
  output        = "./generated/mainClient"
}

generator giraphql {
  provider     = "prisma-giraphql-types"
  clientOutput = "./generated/mainClient"
  output       = "./giraphql-types.ts"
}

```

I have set the client output explicitly since my project contains multiple prisma schemas. However this setup has worked previously very well and had no problems with the giraphql type generation. 

Currently the `giraphql-types.ts` is only messing up the client imports and looks like this:
```ts
import type { , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,  } from "./generated/mainClient";
...
```

Current dep versions which could have side effects on this issue:
```json
{
         "dependencies": {
		"@giraphql/core": "^2.22.0",
		"@giraphql/plugin-errors": "^2.13.0",
		"@giraphql/plugin-prisma": "^0.14.0",
		"@giraphql/plugin-relay": "^2.19.0",
		"@giraphql/plugin-scope-auth": "^2.14.0",
		"@giraphql/plugin-simple-objects": "^2.13.0",
		"@giraphql/plugin-smart-subscriptions": "^2.11.0",
		"@giraphql/plugin-validation": "^2.16.0",
		"@prisma/client": "^3.7.0",
		"graphql": "^15.6.0",
	},
	"devDependencies": {
		"prisma": "^3.7.0",
		"ts-node": "^10.2.1",
		"typescript": "^4.4.3"
	}
}
```

**Comment by hayes** [comment]
I think you may just need to upgrade typescript.  There was a breaking change in the complier API in a recent minor version, and unfortunately there wasn't a good way to support both the old and new typescript apis.  I probably should add the new minimum typescript version to the docs and also include it in the peer deps of this package.

**Comment by baristikir** [comment]
@hayes thanks! Can confirm upgrading the typescript version solved it.
