### ISSUE TITLE
Errors plugin - Incorrect error type

### ISSUE THREAD

**Issue by gino** [hayes/giraphql#253]
Hi there,

I am using the errors plugin and used the code example from the [Recommended usage](https://giraphql.com/plugins/errors#recommended-usage) section from the docs. And trying the following query:

```graphql
{
  helloWithMinLength(name: "w") {
    ... on LengthError {
      message
      minLength
      __typename
    }
    
    ... on BaseError {
      message
      __typename
    }
    
    ... on QueryHelloWithMinLengthSuccess {
      data
    }
  }
}
```

This query does throw an error, like expected. But unfortunately, the error is not of the `LengthError` type:
![image](https://user-images.githubusercontent.com/23482089/147243191-5c3a8eb6-66f3-4a61-994e-fe233816f023.png)

This also results in not being able to query the extra `message` parameter on the `LengthError` type.

Not too sure what causes this issue to happen.

**Comment by hayes** [comment]
I've tried to reproduce this locally, and so far everything is working as expected. Any chance you can share the repo you are working in?

Might also be helpful to know the rest of you setup (what you are using to build/run your app, what server/framework you are using to execute your schema, etc.  

Can you confirm that you are targetting es6 or higher when you compile your app?  The errors plugin uses a feature that is not downleveled safely if you are targetting an older version of javascript

**Comment by gino** [comment]
> Can you confirm that you are targetting es6 or higher when you compile your app? The errors plugin uses a feature that is not downleveled safely if you are targetting an older version of javascript

@hayes, I just checked my `tsconfig.json` and figured out that there was no `target` property at all, which defaults to `ES3`. I've added the property and set it to `ES6` which solved my issue. Thanks a lot, didn't realize I missed this property, makes sense now!
