### ISSUE TITLE
Prisma Plugin by builder.queryType getting type error

### ISSUE THREAD

**Issue by j3sch** [hayes/giraphql#256]
hi, 

I implemented GiraphQL with the Prisma plugin in Nextjs. 

I wanted to try out the examples described here: https://giraphql.com/plugins/prisma#example.
I adapted these example to my Prisma schema. 

```
builder.queryType({
	fields: (t) => ({
		me: t.prismaField({
			type: 'User',
			resolve: async (query, root, args, ctx, info) =>
				prisma.user.findUnique({
					where: { id: ctx.id },
				}),
		}),
	}),
});

```
Here by
```
resolve: async (query, root, args, ctx, info) =>
	prisma.user.findUnique({
		where: { id: ctx.id },
	}),
}),
```
I get the following error: 

Type 'Promise<User | null>' is not assignable to type 'MaybePromise<readonly unknown[]> | null | undefined'.
Type 'Promise<User | null>' is not assignable to type 'Promise<readonly unknown[]>'.
Type 'User | null' is not assignable to type 'readonly unknown[]'.
Type 'null' is not assignable to type 'readonly unknown[]'.ts(2322)

My Prisma Object:
```
builder.prismaObject('User', {
	name: 'User',
	findUnique: (user) => ({ id: user.id }),
	fields: (t) => ({
		id: t.exposeID('id'),
		name: t.exposeString('name'),
	}),
});
```

GraphQL Schema:
```
type Query {
  me: User!
}

type User {
  id: ID!
  name: String!
}
```

My only Prisma Schema Model:
```
model User {
  id        String   @id @default(uuid())
  name     String @db.VarChar(100)
  createdAt DateTime @default(now())
}
```

I would be grateful if someone could help me. 
Cheers.

**Comment by hayes** [comment]
Can you make sure strict mode is enabled in your tsconfig, and that typescript. prisma and all giraphql packages are up to date?

**Comment by hayes** [comment]
This looks like it's either an issue with the generated types, or typescript not being in strict mode.  If you tsconfig looks good, and your packages are up to date, open up the generated types file (where you import PrismaTypes from when setting up the builder) and make sure that looks correct.

**Comment by j3sch** [comment]
Thank you very much for the fast response.

I found out after reinstalling the node_modules the error was gone. 

Than after I added or removed a packages, the same error occurred again.

**Comment by hayes** [comment]
Make sure you run prisma generate any time you change node_modules to
regenerate your Prisma client and types for your Prisma schema

**Comment by neongreen** [comment]
Had the same issue and it got fixed by upgrading to prisma 4 and switching from `findUnique({..., rejectOnNotFound: true})` to `findUniqueOrThrow({...})`.

(The latter is what the docs say to use as well, but I assumed it'd work anyway, and it didn't)
