### ISSUE TITLE
[Errors/Relay Plugin] Naming of Result type

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#258]
I noticed that when using the errors plugin (with the relay mutation plugin), the result type is prefixed with `Mutation`. Is this necessary? It makes for a less readable schema IMO.

```graphql
type Mutation {
  fooBar(
    input: FooBarInput!
  ): MutationFooBarResult!
}
```

**Comment by hayes** [comment]
You can manually set the name of the result type, it defaults to `${ParentType}${FieldName}Result` to avoid collisions because it is not smart enough to combine result types across multiple fields.

To set the result type name you can set
```ts
builder.mutationType({
  fields: (t) => ({
    example: t.string({
      errors: {
        types: [Error],
        union: { name: 'NameOfResultUnion', ...otherOptionsForUnion },
        result { name: 'NameOfSuccessfulResultType', ....otherOptionsForSucess },
      },
      resolve: (parent, { name }) => {...},
    }),
  }),
});
```
