### ISSUE TITLE
Relay Plugin: Make ID encoding optional

### ISSUE THREAD

**Issue by kesne** [hayes/giraphql#26]
Right now there's a handful of cases where the ID of relay nodes / cursors are base64 encoded. While at times this makes sense, there are cases where the ID type is already entirely opaque, and does not require encoding. It would be good to have a option to disable the automatic encoding of these values

**Comment by hayes** [comment]
2.0 has the ability to customize the id encoding (PR above).  Leaving this open to track auto-decoding global ids when used as in arguments. I've got a few ideas around that I want to try soon
