### ISSUE TITLE
Can't define extra fields with relay plugin on connection or edge

### ISSUE THREAD

**Issue by RyanTheAllmighty** [hayes/giraphql#40]
Looking at the docs for the relay plugin at https://giraphql.com/plugins/relay#creating-connections and it shows a brief snippet about defining extra fields on Connection/Node (https://github.com/hayes/giraphql/blame/main/docs/plugins/relay.md#L140-L153).

Defining an addition field like below (snipped down to clean it up for visibility):

```
builder.queryField('test', (t) =>
    t.connection(
        {
            type: 'Test',
            resolve: (root, args, ctx) => {
                return resolveOffsetConnection(
                    {
                        args,
                    },
                    () => {
                        return [];
                    },
                );
            },
        },
        {
            fields: () => ({
                totalCount: t.int({
                    resolve: (root) => {
                        return 100;
                    },
                }),
            }),
        },
        {},
    ),
);
```

This results in no additional fields in the generated schema.

Is this an oversight in the documentation or am I doing something wrong/misunderstanding the docs?

**Comment by hayes** [comment]
This was a complete oversight on my part.  I wrote some of the docs before implementing the feature, and forgot to actually hook it up (even though the types are correct).  Just released a fix in [`@giraphql/plugin-relay@2.0.4`](https://github.com/hayes/giraphql/blob/main/packages/plugin-relay/CHANGELOG.md#204---2021-03-28)

**Comment by hayes** [comment]
let me know if that works for you, sorry for any confusion.

**Comment by RyanTheAllmighty** [comment]
Yup, looks good. Working as expected now.

Thanks for the super quick fix 👍🏻
