### ISSUE TITLE
Weird VsCode error with SimpleAuthPlugin

### ISSUE THREAD

**Issue by kush-daga** [hayes/giraphql#44]
### Error 
Hey I am new to this and have started using GiraphQL recently.
While using SimpleAuthPlugin in my project, even though I am declaring the types in SchemaBuilder for my AuthScopes, I am getting this vs code error for authScopes inside the queryFields or mutationFields.

The plugin is working as expected when I make graphql requests, just vs code is showing this typescript error which is very weird.

Error Shown -
![image](https://user-images.githubusercontent.com/40840079/116761411-35f26a00-aa35-11eb-95a5-7ed79fd7652d.png)

Text - 
```
Type '{ user: true; }' is not assignable to type 'FieldAuthScopes<ExtendDefaultTypes<{ DefaultInputFieldRequiredness: true; Context: { req: IncomingMessage; res: OutgoingMessage; user?: User; session?: Session; }; Scalars: { ...; }; AuthScopes: { ...; }; }>, {}, InputShapeFromFields<...>>'.
  Object literal may only specify known properties, and 'user' does not exist in type 'FieldAuthScopes<ExtendDefaultTypes<{ DefaultInputFieldRequiredness: true; Context: { req: IncomingMessage; res: OutgoingMessage; user?: User; session?: Session; }; Scalars: { ...; }; AuthScopes: { ...; }; }>, {}, InputShapeFromFields<...>>'.ts(2322)
global-types.d.ts(35, 13): The expected type comes from property 'authScopes' which is declared here on type 'QueryFieldOptions<ExtendDefaultTypes<{ DefaultInputFieldRequiredness: true; Context: { req: IncomingMessage; res: OutgoingMessage; user?: User; session?: Session; }; Scalars: { ...; }; AuthScopes: { ...; }; }>, ObjectRef<...>, true, InputFieldMap, unknown>'

```

### My Builder file
 
![image](https://user-images.githubusercontent.com/40840079/116761569-a26d6900-aa35-11eb-8d6e-127cc8dbbec6.png)

**Comment by kush-daga** [comment]
### Output for `npx tsc --project ./`

![image](https://user-images.githubusercontent.com/40840079/116762335-b74afc00-aa37-11eb-8589-a792ee78595e.png)

**Comment by kush-daga** [comment]
Ok so apparently changing `strict:false` to `strict:true` in my projects `tsconfig.json` fixes this issue, is this intended?

**Comment by hayes** [comment]
It is not intended, but not entirely surprising.  GiraphQL is designed around type safety and uses a lot of typescripts features.  Disabling strict mode in typescript causes a lot of thing to work differently.  In general I would recommend using strict mode if at all possible.

If you are not able to use strict mode, I can investigate further, but you will lose a lot of type safety, and I am not sure if there will be an easy workaround.

**Comment by hayes** [comment]
I should probably investigate a bit and update the docs on what things might not work without strict mode.

**Comment by kush-daga** [comment]
Awesome, yes documentation should help, and I'll use strict mode then, thanks for clarifying :)

**Comment by litewarp** [comment]
Just noting this here, but the type definitions for extending the globalConnectionFields will not work unless `"strict": true` is set in your tsconfig.

**Comment by hayes** [comment]
Added a troubleshooting doc, and a step to the getting started section that mentions using struct mode
