### ISSUE TITLE
Adding a scalar from a library

### ISSUE THREAD

**Issue by mmahalwy** [hayes/giraphql#52]
When using a library such as `graphql-scalars` for the JSON scalar, it's unclear how to add it to Giraphql. I tried this
```ts
const JsonType = builder.scalarType('GraphQLJSON', GraphQLJSON);
```

which resulted to error below:
![image](https://user-images.githubusercontent.com/3749095/118422964-ed63bf00-b678-11eb-83b0-b35f60c05319.png)

Seems like the type needs to change to: 
```ts
description?: string | null;
extensions?: Readonly<Record<string, unknown>> | null;
```

Narrowed it down to this:
https://github.com/hayes/giraphql/blob/1da1283475089311aed09a1c5079007e9abb7abf/packages/core/src/types/global/type-options.ts#L28

**Comment by hayes** [comment]
There are 2 methods:

scalarType let's you define your own scalars by implementing methods directly.

addScalarType let's you add existing scalar definitions.
https://giraphql.com/guide/scalars#adding-graphql-scalars

**Comment by mmahalwy** [comment]
Awesome, thank you @hayes!
