### ISSUE TITLE
Cannot read property 'toString' of undefined when building schema

### ISSUE THREAD

**Issue by mmahalwy** [hayes/giraphql#56]
See:
![image](https://user-images.githubusercontent.com/3749095/118712005-1ac57f80-b7d5-11eb-9f9a-98bfa64c9055.png)

**Comment by mmahalwy** [comment]
Happening because of circular dependencies.

**Comment by hayes** [comment]
Interesting.  This path should only get called when creating a (different) error.  It is trying to create a name for a ref which hasn't been implemented, but the ref is undefined.  My guess would be some sort of circular import causing undefined to be passed as a ref because the file it was imported from hasn't run.  Can't tell for sure what's causing it from that stack trace.

**Comment by hayes** [comment]
Error message in this case should be better, and I should probably just have a runtime check to disallow undefined as ref

**Comment by mmahalwy** [comment]
Once I moved the objects into their own files, this error went away. I do think it's circular import is the problem.

**Comment by hayes** [comment]
How were the problematic refs being used?  Anything inside a fields function should alread get deferred to allow circular references.

**Comment by hayes** [comment]
Actually, I think I see how this could still happen.  I'm on a road trip, but will work on a fix soon

**Comment by mmahalwy** [comment]
No worries. I was able to replicate it with this:

```ts
export const ApplicationFieldConfigInput = builder
  .inputRef<ApplicationFieldConfig>('ApplicationFieldConfigInput')
  .implement({
    fields: (t) => ({
      name: t.string({ required: true }),
      label: t.string({ required: true }),
      type: t.field({ required: true, type: ApplicationFieldConfigTypeEnum }),
      fieldPath: t.string({}),
      fieldHandlers: t.field({
        required: true,
        type: [ApplicationFieldConfigFieldHandlerEnum],
      }),
      options: t.stringList({ required: true }),
      modelPath: t.string({}),
      docspringPath: t.string({}),
      visibleIf: t.string({}),
      requiredIf: t.string({}),
      validations: t.string({}),
      defaultRequired: t.boolean({ defaultValue: false }),
      defaultShow: t.boolean({ defaultValue: true }),
      defaultLocked: t.boolean({ defaultValue: false }),
      children: t.field({ required: true, type: [ApplicationFieldConfigInput] }),
    }),
  });
```

Recursive input is throwing it off too.

**Comment by hayes** [comment]
Pushed a new version that should help with these.  There was a bit of a regression here, but added a test specifically for recursive imports.

**Comment by hayes** [comment]
I think my recursive inputs split the implement step into a separate statement which is why they were not failing

**Comment by mmahalwy** [comment]
Woohoo! Fixed! Thanks a bunch for this!
