### ISSUE TITLE
ObjectRef.implements returns any

### ISSUE THREAD

**Issue by delaneyj** [hayes/giraphql#59]
```ts
 const Author = builder.objectRef<AuthorModel>('Author').implement({
    description: 'A writer.',
    fields: (t) => ({
      id: t.exposeID('id', {}),
      firstName: t.exposeString('firstName', {}),
      lastName: t.exposeString('lastName', {}),
      posts: t.field({
        type: [Post],
        args: {
          findTitle: t.arg.string({
            description: 'if empty then it grabs all',
          }),
        },
        resolve: (author, { findTitle }) => {
          let pp = db.posts.filter((p) => p.authorID === author.id)
          if (findTitle) {
            pp = pp.filter((p) => p.title === findTitle)
          }
          return pp
        },
      }),
    }),
  })

  const Post = builder.objectRef<PostModel>('Post').implement({
    description: 'Post from writer',
    fields: (t) => ({
      id: t.exposeID('id', {}),
      title: t.exposeString('title', {}),
      author: t.field({
        type: Author,
        resolve: (post) => {
          const author = db.authors.find((a) => a.id === post.authorID)
          if (!author) throw new Error('bad author id')
          return author
        },
      }),
    }),
  })
```

generates the error
```json
{
	"resource": "src/graphql/giraph/test.ts",
	"owner": "typescript",
	"code": "7022",
	"severity": 8,
	"message": "'Author' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 9,
	"endLineNumber": 11,
	"endColumn": 15
}
```

However change to ...
```ts
...
const Author = builder.objectRef<AuthorModel>('Author')
Author.implement({...})
...
```
resolves the errors.  The first way [matches the docs](https://giraphql.com/guide/objects#using-refs) and is cleaner.  Am I missing something?

**Comment by hayes** [comment]
Interesting... I should probably add a note to the docs about this specific case.  The root of this is in the circular reference.  Even though logically we know that the options passed to implement won't affect the type of Author, typescript can't resolve the shape of Author until it has resolved the shape of the options object.  The options objects for author and post circularly reference each other, so typescript can't properly resolve the types.  I don't see an obvious way around this at the moment, but I can add a note to the docs to make this more explicit.  Seems like for circular references you'll just have to split at least one of the types into 2 statements as you did above.

**Comment by hayes** [comment]
added a note to the docs

**Comment by homoky** [comment]
Is there a workaround for dataloader as well?

**Comment by hayes** [comment]
I'm away from my computer right now, so can't give a complete answer or test right now, but, you can pass a ref instead of a name to loadable object.

Basically export const Composer = builder.objectRef<ComposerType>('Composer')

And then just do builder.loadableObject(Composer, {...})

Let me know if works, if not I can take a look on Monday

**Comment by homoky** [comment]
No rush @hayes, enjoy weekend. :D I opened #358 to keep this in one place separate of this issue.
