### ISSUE TITLE
Possible to use graphql-scalars' UUID as ID

### ISSUE THREAD

**Issue by delaneyj** [hayes/giraphql#62]
https://giraphql.com/guide/scalars shows creating your own scalars but not how to use as an ID.

Coming from [gqlgen](https://gqlgen.com/) I used to being able to set the `ID!` fields to validate as UUID from both the query and mutation side.  I did see how to use the validate plugin to check input args for uuids, but not how to set a type for IDs.

Specifically I was trying to add [Graphql-Scalars UUID ](https://www.graphql-scalars.dev/docs/scalars/uuid).  

```ts
import { UUIDResolver } from 'graphql-scalars'

const builder = new SchemaBuilder<{
    Scalars: {
      UUID: {
        Input: typeof UUIDResolver
        Output: typeof UUIDResolver
      }
    }
  }>({
    plugins: [ValidationPlugin],
  })
const uuid = builder.addScalarType('UUID', UUIDResolver, {})
```
does not error out, however I'm unclear how to use in a `t.exposeID`.
```ts
fields: (t) => ({
      id: t.exposeID('id', {
        type: uuid,
      }),
```
Doesn't work but I'm not sure what it should look like.  Just want to make sure it I can't give an invalid UUID as part of the resolver.  In go UUID as an explicit type extending byte[16] and would like that level of explicitness.  Was hoping using graphql-scalars would help enforce that.

**Comment by hayes** [comment]
I think you want t.expose rather than t.exposeID

**Comment by hayes** [comment]
And then type can be either uuid as in your example, or just 'UUID' as a string

**Comment by hayes** [comment]
Looking at your setup, where you have `typeof UUIDResolver` you probably want to use something else.  I think that will expect a function to be returned from your resolver.  The type there should just be the primative type expected (string probably)

**Comment by delaneyj** [comment]
In gqlgen the uuid.UUID makes sense because its generating the resolver boilerplate for you.  So everywhere you use `ID!` in the schema it replaced the args with `uuid.UUID` in the resolvers/objectTypes.  I was hoping for something similar here where you can say something like "i know gql ID is just an alias for string but make sure its typed as a UUID`.  If I'm not explaining the intent well enough please let me know.

**Comment by hayes** [comment]
So you are trying to automatically replace all instances of ID with UUID in your schema, or are you just trying to add custom runtime validation to the ID scalar?

**Comment by delaneyj** [comment]
It appears I'm just dense.  Using a resolver for id ala ` id: t.id({ resolve: (a) => a.id.toString() }),` is perfectly fine.  Apologize, just trying to get my head around the code first coming from SDL first, plus in a different language.  In this case the scalar type isn't really even needed.  I was complecting the internal types with the resolvers types, because with SDL first that kinda happens with the generation.  Its very exciting and interesting because by being explicit there it probably will actually mean less code than the generated approach.

**Comment by hayes** [comment]
No worries.  It gets kinda confusing with graphql types, typescript types, runtime validation, data-models being different from your schema representation, etc... it's a lot to keep track of at first.
