### ISSUE TITLE
inputField method

### ISSUE THREAD

**Issue by ragnorc** [hayes/giraphql#66]
There exist methods such as `objectField` and `mutationField` that allow iterative additions of fields to existing types.

Is there a way to do the same thing for `inputType` such that one could call a method `inputField`? I cannot find it in the API, is it not implemented or just done differently?

**Comment by hayes** [comment]
Input types can't be changed after they are defined because the definition defines the shape (type) of the input type.  If you later add more input fields, the types for the input type when used as an arg wouldn't be correct.

**Comment by hayes** [comment]
Going to close this, but let me know if you have any more questions!
