### ISSUE TITLE
Globally extend connections?

### ISSUE THREAD

**Issue by litewarp** [hayes/giraphql#67]
I have a use case where we add the totalCount and paginatedCursors to relay connections (inspired by [artsy](https://artsy.github.io/blog/2020/01/21/graphql-relay-windowed-pagination/)) such that the type for a "connection" field is roughly:

```JSX
type PageCursors {
  ...
}

type SomeConnection {
  edges: [SomeEdge!]
  pageInfo: PageInfo!
  totalCount: Int!
  pageCursors: PageCursors!
}
```

I know that graphql-nexus lets you [globally extend the connection type](https://nexusjs.org/docs/plugins/connection#extending-connection--edge-types), but I could not figure out if that was an option with GiraphQL, and/or how one might go about extending the connection type globally. 

Also, I'm actually enjoying building a Relay API with GiraphQL, so great work!

**Comment by hayes** [comment]
Unfortunately there isn't a great way to do this right now.  It should be pretty easy to add though.  I think to support this I would need to add 2 things: a way to add fields to all connection objects, and a way to extend the type for connections so that a connection resolver can be expected to return objects with additional properties.

**Comment by hayes** [comment]
I'll try to find some time to work on this next week

**Comment by litewarp** [comment]
Thanks! I appreciate the quick response. 

On a somewhat related topic (I can open a separate PR if you wish), is there an example or documentation of splitting up the builder across multiple files. I can only get the schema to load when all my builder calls come from an instance initialized in the same file. Or a discord where I could ask questions?

**Comment by hayes** [comment]
Building a schema requires all types to be defined using the same builder instance, but you can split that actual definitions into multiple files.

There are some tips on ways you can structure your app in https://giraphql.com/guide/app-layout

For concrete examples there are example apps in the test directory for each package you could look at (only a few of these split things I to many files). Eg https://github.com/hayes/giraphql/tree/main/packages/core/tests/examples/giraffes

For questions, I don't currently have a discord, for now I would recommend https://github.com/hayes/giraphql/discussions

**Comment by litewarp** [comment]
Thanks! The example helped. The difference was importing the *entirety* of the file instead of just exports -- ie, 

import "./person"

NOT import * from './person'

**Comment by hayes** [comment]
PR: https://github.com/hayes/giraphql/pull/68/files

**Comment by hayes** [comment]
published as
 - @giraphql/deno => 2.3.0
 - @giraphql/plugin-dataloader => 2.2.3
 - @giraphql/plugin-relay => 2.3.0

docs: https://giraphql.com/plugins/relay#extending-all-connections
