### ISSUE TITLE
Global ID "VXNlck5vZGU6MQ==" is resulting in "Error: Invalid offset cursor OffsetConnection:"

### ISSUE THREAD

**Issue by NICHTJ3** [hayes/giraphql#69]
My global id which actually decodes to "UserNode:1" is throwing an error due to this line. Is this logic actually correct?
https://github.com/hayes/giraphql/blob/987b78e9195d1cbfc4c6f31e6b7f37cf8f869bb2/packages/plugin-relay/src/utils/connections.ts#L104

**Comment by NICHTJ3** [comment]
I did some more looking through the code base and found that you can only use cursors taken from the pageInfo section. I think traditionally you can use the id's from the nodes but I could be wrong

**Comment by NICHTJ3** [comment]
Scratch that I was trying to use the ID which of course doesn't work... It's not a cursor 🤦

**Comment by NICHTJ3** [comment]
At least this will probably help someone else come to this realization faster

**Comment by hayes** [comment]
In some specific cases it could make sense to use IDs as cursors, but there are tons of edge cases and foot guns, so most of the time it's better to force users to use your cursors from pageInfo.  You can always write your own version of the connection helpers, they are pretty simple
