### ISSUE TITLE
[Relay] Guidance of generalizing plugin usage

### ISSUE THREAD

**Issue by delaneyj** [hayes/giraphql#81]
I've gotten a version of the relay spec working with a SQL database using `pg-sql2`.  It's working great and the backend is generic enough that with a little magic I think it could work in 90% of my cases.  The issue is I wanted to move t.connection into a helper function that filled out the specific but so far have gotten lost in a quagmire of types and have tried many ways but think I'm overcomplicating it.

Here is the working version
```ts
 const User = builder.loadableObject('User', {
    load: (ids: string[], ctx: Context) => loadByIDs<IUser>(ids, ctx),
    fields: (t) => ({
      id: t.exposeID('id', {}),
      name: t.exposeString('name', {}),
      ...
      fooBars: t.connection(
        {
          type: FooBar,
          resolve: async (parent, args, ctx) => {
            const { first, last, before, after }: DefaultConnectionArguments = args

            if (first && last) throw new Error(`shouldn't have both first and last in same query`)

            let filter = emptySQLQuery
            if (after && validate(after)) {
              filter = sql.query`AND r.from_agg_id > ${sql.value(after)}`
            } else if (before && validate(before)) {
              filter = sql.query`AND r.from_agg_id < ${sql.value(before)}`
            }

            let orderLimit = emptySQLQuery
            if (first && first > 0) {
              orderLimit = sql.query`ORDER BY r.updated_at ASC\nLIMIT ${sql.value(first + 1)}`
            } else if (last && last > 0) {
              orderLimit = sql.query`ORDER BY r.updated_at DESC\nLIMIT ${sql.value(last + 1)}`
            }
            const relationship = sql.value('owner')
            const fromType = sql.value(aggName.IFooBar)
            const toAggID = sql.value(parent.id)

            const q = sql.query`
    SELECT r.from_agg_id id
    FROM relationships r 
    WHERE r.relationship = ${relationship}
    AND r.from_type  = ${fromType}
    AND r.to_agg_id  = ${toAggID}
    ${filter}
    ${orderLimit}
    `
            const { text, values } = sql.compile(q)
            const cfg = { text, values }

            const { rows, rowCount } = await ctx.sql.transaction(async (tx) => await tx.query(cfg))

            let hasNextPage = false
            let hasPreviousPage = false

            if (first && first + 1 === rowCount) {
              hasNextPage = true
              rows.splice(-1)
            } else if (last && last + 1 === rowCount) {
              hasPreviousPage = true
              rows.splice(-1)
            }

            if (last) rows.reverse()

            const edges = rows.map(({ id }) => ({
              cursor: id,
              node: id,
            }))

            let startCursor = rows.length ? rows[0].id : null
            let endCursor = rows.length ? rows[rows.length - 1].id : null

            const pageInfo: PageInfoShape = {
              hasNextPage,
              hasPreviousPage,
              startCursor,
              endCursor,
            }

            return { pageInfo, edges }
          },
        },
        {},
        {},
      ),
    }),
  })
```

Closest to method types I've gotten is 
```ts
async function makeRelationship<
Types extends SchemaTypes, Shape,
Type extends OutputType<Types>,
> (
  t: GiraphQLSchemaTypes.ObjectFieldBuilder<Types, Shape>,
fromType:Type,
fromTypeName:string
){
 return t.connection(
    {
      type: fromType,
      resolve: async (parent, args, ctx) => {
        const { first, last, before, after }: DefaultConnectionArguments = args
        ...
```
But the errors just keep stacking the more I try.  I understand this is a very hard typing problem but would really like to extract this out as otherwise the c/p would be prohibitive (I'm having to deal with a 2500 table legacy db that i can not change).  I <3 using GiraphQL as the type check is just amazing, but I feel like I'm stepping into a quagmire and feel like I'm missing some key info.

**Comment by hayes** [comment]
On mobile so I can't type of a full answer, and not sure if I fully understand the issue, but you could try making a helper function that takes 2 object refs instead (types as a ref of {} or something similarly generic).  The helper could then call `builder.objectField(ref1, name, t => t.connection({ type: ref2, ... `.

I think this would likely be a bit easier to type correctly.  Helper methods are kind of complicated with GiraphQL because they are often inherently not type safe.

**Comment by hayes** [comment]
Using ObjectRef<{}> should be pretty easy because it doesn't require SchemaTypes, and if import builder into where you define your help and use it directly rather than passing it as an arg, you shouldn't need any other generics or types to make things work.

**Comment by delaneyj** [comment]
With that I'm MUCH closer.  No errors if I use the `F extends ObjectRef<{id:string}>` and cast `parent` to an any to use the `id` field.  If I use `ObjectRef<{id:string}>` it complains about `Type 'string | IUser' is not assignable to type '{ id: string; }'.` when I go to use it.

Helper methods are kind of complicated with GiraphQL because they are often inherently not type safe.
```ts
function generateRelayRelationship<F extends ObjectRef<{id:string}>, T extends ObjectRef<{}>>(
  builder: Builder,
  fromTypeAggName: string,
  from: F,
  to: T,
  fieldName: string,
) {
  builder.objectField(from, fieldName, (t) =>
    t.connection(
      {
        type: to,
        resolve: async (parent, args, ctx) => {
          const { first, last, before, after }: DefaultConnectionArguments = args

          if (first && last) throw new Error(`shouldn't have both first and last in same query`)

          let filter = emptySQLQuery
          if (after && validate(after)) {
            filter = sql.query`AND r.from_agg_id > ${sql.value(after)}`
          } else if (before && validate(before)) {
            filter = sql.query`AND r.from_agg_id < ${sql.value(before)}`
          }

          let orderLimit = emptySQLQuery
          if (first && first > 0) {
            orderLimit = sql.query`ORDER BY r.updated_at ASC\nLIMIT ${sql.value(first + 1)}`
          } else if (last && last > 0) {
            orderLimit = sql.query`ORDER BY r.updated_at DESC\nLIMIT ${sql.value(last + 1)}`
          }
          const relationship = sql.value('owner')
          const fromType = sql.value(fromTypeAggName)

          const toAggID = sql.value(parent.id)

          const q = sql.query`
SELECT r.from_agg_id id
FROM relationships r 
WHERE r.relationship = ${relationship}
AND r.from_type  = ${fromType}
AND r.to_agg_id  = ${toAggID}
${filter}
${orderLimit}
`
          const { text, values } = sql.compile(q)
          const cfg = { text, values }

          const { rows, rowCount } = await ctx.sql.transaction(async (tx) => await tx.query(cfg))

          let hasNextPage = false
          let hasPreviousPage = false

          if (first && first + 1 === rowCount) {
            hasNextPage = true
            rows.splice(-1)
          } else if (last && last + 1 === rowCount) {
            hasPreviousPage = true
            rows.splice(-1)
          }

          if (last) rows.reverse()

          const edges = rows.map(({ id }) => ({
            cursor: id,
            node: id,
          }))

          let startCursor = rows.length ? rows[0].id : null
          let endCursor = rows.length ? rows[rows.length - 1].id : null

          const pageInfo: PageInfoShape = {
            hasNextPage,
            hasPreviousPage,
            startCursor,
            endCursor,
          }

          return { pageInfo, edges }
        },
      },
      {},
      {},
    ),
  )
}
```

> Feels much closer but still wanted retain the type info within the helper function.
With the use of generics I'm not sure why that's the case, but then again this is using some heavy TS voodoo.

**Comment by hayes** [comment]
Where do you get that error? I can't see from from your example where that would be happening.

**Comment by delaneyj** [comment]
`<F extends ObjectRef<{id:string}>` causes the error.  If I use the empty interface version I don't get the error, however I do lose the type checking on the parent argument of the resolver

**Comment by delaneyj** [comment]
You're 100% right, it's in the calling of the helper...

![image](https://user-images.githubusercontent.com/438252/121407983-b9e12100-c914-11eb-9b50-522a7ad4d571.png)

**Comment by hayes** [comment]
I see! This makes sense now... This is something weird about loadable objects.  They are somewhat unique in that resolvers can return the object or id directly.  You are getting the type that is returnable from a resolver for user rather than the type that you expect as the parent arg.  Let me check to see what an easy fix for this would be.

**Comment by hayes** [comment]
@delaneyj wasn't a great way to handle this as is, made some changes I think should help:

https://github.com/hayes/giraphql/pull/82

With the preview version in that PR, you should be able to use `ObjectRef<unknown, { id: string }>`.  Basically this PR plumbs some logic for refs that have a separate parent type from a resolver return type through lower levels of GiraphQLs type system.  The second generic for ObjectRef now specifies the parent shape.

**Comment by hayes** [comment]
Let me know if that works for you. I haven't tested it very thoroughly yet.

**Comment by hayes** [comment]
Release the change linked above, and added some docs on creating helpers for applying shared fields here: https://giraphql.com/guide/patterns#sharing-fields-between-types  let me know if you are still running into issues

**Comment by delaneyj** [comment]
Sorry was out, nice!  That was really fast, and yes it appears to be working correctly!
