### ISSUE TITLE
Resolving circular dependency

### ISSUE THREAD

**Issue by mmahalwy** [hayes/giraphql#84]
I am having a circular dependency error happening. I have two files:

ApplicationObject.ts - has the Application object definition, references `ClientObject`
ClientObject.ts - has the Client object definition, references `ApplicationObject`

Weirdly, because of this dependency, both objects show up as `any`. Thoughts on how to solve this? I tried splitting `objectRef` and `implement` but didn't work:

```ts
export const ApplicationObjectRef = builder.objectRef<Application>('Application');

export const ApplicationObject = ApplicationObjectRef.implement({
  fields: (t) => ({
    id: t.exposeID('id', {}),
...
```

**Comment by Brendonovich** [comment]
Just ran into this problem, would love to see a solution

**Comment by mmahalwy** [comment]
Should mention that I am referencing the objects via 
```ts
t.field({ type: ClientObject ... })
```

**Comment by mmahalwy** [comment]
@Brendonovich @hayes i guess one way to resolve this is:

src/schema.ts
```ts
const builder = new SchemaBuilder({});
```
src/objects.ts
```ts
const ApplicationObject = builder.objectRef<Application>('Application');
const ClientObject = builder.objectRef<Client>('Client');
```

src/resolvers/ApplicationResolver.ts
```ts
builder.objectType(ApplicationObject, {
  description: 'Long necks, cool patterns, taller than you.',
  fields: (t) => ({
    client: t.field({ type: ClientObject, ... }),
  }),
});

builder.queryFields((t) => ({
  giraffe: t.field({
    type: ApplicationObject,
    resolve: () => ({
      name: 'James',
      birthday: new Date(2012, 11, 12),
      height: 5.2,
    }),
  }),
}));
```

**Comment by hayes** [comment]
@mmahalwy 

try splitting the implementation slightly differently:

```ts
export const ApplicationObject = builder.objectRef<Application>('Application');

ApplicationObject.implement({
  fields: (t) => ({
    id: t.exposeID('id', {}),
```

**Comment by hayes** [comment]
This is a somewhat unfortunate limitation of typescript.  Currently there are ~3 work arounds I can think of:

1. Split up the definitions in your circular graph like I did above with `objectRef` and `implement` (the important part is using the return value of objectRef NOT implement)
2. Use SchemaTypes for one of your types (and reference the type via a string name, rather than a ref)
3. Use `builder.objectField` to add the circular field to one of your object types.

**Comment by mmahalwy** [comment]
Mind showing an example of the third option?

**Comment by hayes** [comment]
```ts
export const ApplicationObject = builder.objectRef<Application>('Application').implement({
 fields: (t) => ({ ...otherFields }),
});

export const ClientObject = builder.objectRef<Client>('Client').implement({
 fields: (t) => ({
    application: t.field({ type: ApplicationObject, ... })
  }),
});

builder.objectField(ApplicationObject, 'client', (t) => t.field({ type: ClientObject, ... }));
```

**Comment by mmahalwy** [comment]
@hayes got it. Thank you! I ultimately went down the path of having all the `objectRef`s and enums in a single file, then defined the implementations in separate files or within the resolver files.
