### ISSUE TITLE
Error while using simpleInterfaces

### ISSUE THREAD

**Issue by NICHTJ3** [hayes/giraphql#85]
When not using interfaces created using the simple object plugin using objects created in the simple object plugin I get the error 
`type [...] not assignable to type '"Object shape must extends Interface shape"'`

e.g.
```js
export const PageInterface = builder.simpleInterface('Page', {
  fields: (t) => ({
    posts: t.string({ }),
  }),
});

export const UserEntity = builder
  .objectRef<User>('User')
  .implement({
    interfaces: [PageInterface],
    fields: (t) => ({
      id: t.exposeID('id', {}),
      posts: t.string({
        resolve: () => 'hello',
      }),
    }),
  });
```

**Comment by NICHTJ3** [comment]
More context for the error message
<img width="728" alt="Screen Shot 2021-06-19 at 9 48 27 PM" src="https://user-images.githubusercontent.com/39316919/122638425-1ed41c80-d148-11eb-9b87-be699e9b85e0.png">

**Comment by NICHTJ3** [comment]
Ahh so I see you have to create an objectType to use interfaces. Is there a nice way to use interfaces on loadableNodes?

**Comment by hayes** [comment]
The issue you are running into is that your types for the interface and the the object type are not compatible.  Interfaces can implement the resolvers for fields.  To do this, they expect all object types that implement the interface to use a type that extends the type of the interface.   In your example, the simpleInterface call creates an interfaces that is backed by a type like {users: string}.  The simple-objects plugin basically infers a type based on the defined fields.  You User type probably doesn't have a property posts that is a string, which is causing the issue.   To get around this you can create an interface like builder.interfaceRe<unknown>('Page'). implement ({fields: t=> ({ posts: t.string({}}) }).

This interface expects objects to extend unknown, making it compatible with any object type, and should work with loadableObject, or any other way of creating object types 

On mobile so this probably isn't exactly right, but hopefully that gives you an idea of how to get this working.
