### ISSUE TITLE
[Error-Plugin] Documentation example errors are both returning as __typename BaseError

### ISSUE THREAD

**Issue by MollariGaming** [hayes/giraphql#87]
```
"@giraphql/core": "^2.9.0",
"@giraphql/plugin-errors": "^2.1.0",
```

Not sure if documentation error or an error in the plugin itself. From https://giraphql.com/plugins/errors#recommended-ussage are both giving me the __typename of BaseError. I have not had a chance to dive directly into the code just yet but since I was planning on switching to this type of error handing with graphql I wanted to give this a quick test.

I am also getting a type error for the empty errors: {} (documentation or type issue) object under the hello query, easily fixed with adding 

```
  errors: { 
    types: [Error] 
 }
```

![Capture](https://user-images.githubusercontent.com/60820746/123707755-d0054180-d82f-11eb-8df3-ddf510202fbe.PNG)

Overall, great work on the package. Love using it, and it just keeps getting better.

**Comment by hayes** [comment]
Weird.  This works when I run it locally, but in code-sandbox reproduces your issue: https://codesandbox.io/s/thirsty-franklin-xp868?file=/src/index.ts

**Comment by hayes** [comment]
Okay, did some digging.  What's in your tsconfig?  Make sure your target is not set to at least es6 (default is es3)

**Comment by MollariGaming** [comment]
Changing the target to es6 fixed it (tsc --init defaults to es5 in typescript 4.3.4 where it resolves to BaseError for both) Appreciate you looking into it as I just quick threw together a new project to check it out and had not done much for configuration. That also fixed the type error with the empty error object as well, thanks!

**Comment by hayes** [comment]
Re-opening this to track the need for docs update

**Comment by hayes** [comment]
docs updated
