### ISSUE TITLE
Connections on interface

### ISSUE THREAD

**Issue by NICHTJ3** [hayes/giraphql#89]
Is there any way of doing this yet?
```ts
import { builder } from '../builder';
import { PostEntity } from '../entities';

export const PageInterface = builder.interfaceRef('Page').implement({
  fields: (t) => ({
    // eslint-disable-next-line
    posts: t.connection({ type: PostEntity, resolve: () => ({} as any) }),
  }),
});
```

I tried the above but get this error when trying to use it with relay

```
Interface field Page.posts expects type PagePostsConnection! but UserNode.posts is type UserNodePostsConnection!.
```

**Comment by hayes** [comment]
Are defining the field on both the interface and the UserNode?  I think of you omit the field on UserNode it would work, but I suspect you want a different resolver.   I think for now you would need to manually define your connection object and implement the field like any other field.  In general there isn't a way to re-use the connection types for multiple fields which is effectively what you need.  I'll have to think about a solution for this that isn't just manually implementing everything.

**Comment by NICHTJ3** [comment]
My problem is effectively that I have a `Feed` and a `Profile` both of which have posts.

On the client I have a PostList that uses a fragment to get the posts and I wanted to be able to reuse it between the Feed and Profile pages.

But to solve my problem for now what do you mean by manually defining my connection object?

**Comment by NICHTJ3** [comment]
If I can't find a nice solution to this I might just create two separate components for my post lists which might be the more correct thing to do

**Comment by hayes** [comment]
I am thinking about adding an API like:

```ts
const SharedConnection = builder.connectionObject(NumberThing);

builder.queryField('sharedConnection', (t) =>
  t.field({
    type: SharedConnection,
    nullable: true,
    args: {
      ...t.arg.connectionArgs(),
    },
    resolve: (root, args) =>
      resolveOffsetConnection({ args }, ({ limit, offset }) => {
        const items = [];

        for (let i = offset; i < Math.min(offset + limit, 200); i += 1) {
          items.push(new NumberThing(i));
        }

        return items;
      }),
  }),
);
```

Basically this would allow you to define a connection object type that is re-usable in multiple field definitions, adding an API to create connection args.  This would let you define a `PostsConnection` object type, and then use that to define a field on your Page interface, as well as your Profile and Feed objects.  The issue is that currently there is no way to use the same Connection type on multiple fields (a requirement for fields defined on interfaces)

**Comment by NICHTJ3** [comment]
That would be great. This is pretty much the solution I was hoping for 💯

**Comment by hayes** [comment]
I'll try to add this some time this weekend.

**Comment by hayes** [comment]
published a pre-release with the above API.  Version info is in the [PR description](https://github.com/hayes/giraphql/pull/96). Docs are in the first file in the chage-set if you want to try it out
