### ISSUE TITLE
Optional client mutation Id

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#91]
The Input and Payload pattern of the relay mutation helper is very helpful, but the required clientMutationId makes it less generally applicable. An option to omit the client mutation id would be very much appreciated.

**Comment by hayes** [comment]
added a new `clientMutationId` option to `relayOptions` that can be `required` | `optional` | `omit`

**Comment by jamiehodge** [comment]
Thank you so much. I've been really enjoying porting schema to giraphql. It was especially pleasing to see the error plugin compose with the relay mutation helper.

**Comment by hayes** [comment]
awesome, glad to hear it!  plugin composition was one of my big goals when I started building this out.   Thanks for opening these issues, definitely a few rough edges to smooth out to make this all easier to use for more use cases like yours.
