### ISSUE TITLE
Relay connection cursor type

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#94]
The relay connection plugin is using `ID` for cursors. Reading the relay connection spec, it clearly allows for this, but we are currently using `String` and this would be a breaking change for clients. Is it possible to configure this type? If not, we can look at a migration path.

**Comment by hayes** [comment]
That's a great call out.  I think String is a much better option, but would be a breaking change.  I can make it configurable, and will update the docs to recommend using strings in the plugin setup instructions.

**Comment by hayes** [comment]
published a pre-release version with a new options `cursorType`.  Version info is in the [PR description](https://github.com/hayes/giraphql/pull/96).  Let me know if this works for you.

**Comment by eklarskov** [comment]
The pre-releases with `cursorType` work great. Thanks a ton @hayes.
